name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Set environment variable
      run: echo "LENGTH_PASSWORD=12" >> $GITHUB_ENV 

    - name: Run the application
      run: python task.py ${{ env.LENGTH_PASSWORD }}